// Get a User
GET http://localhost:5000/users

###
// Login admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
// Login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ayis@gmail.com",
    "password": "123456"
}

###
// Logout
DELETE http://localhost:5000/logout

###
// Delete User oleh Admin
DELETE http://localhost:5000/users/68fd7b41-ef70-4e68-9356-784679093d69

###
//Check Login
GET http://localhost:5000/me

###
// Get Patients
GET http://localhost:5000/patients